<a href="https://colab.research.google.com/github/shubh28012004/Basics-of-numpy-/blob/main/EDS_1_Basics_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy
is incredibly fast and used as linear algebra for python .

In [2]:
import numpy as np

Numpy has many built-in in functions and capabilities . Important aspects covered are :


1.   vectors
2.   arrays
3.   Number generation



**Numpy Arryas**
essentially comes in two flavours : Vectors and matrices

**Creating NumPy Arrays**

In [3]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [6]:
np.array(my_list)
my_list


[1, 2, 3]

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Built in methods**

1.  arange :- return evenly spaced values within a given interval

In [11]:
np.arange(0,10) # default spacing is 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.arange(0,50,7)

array([ 0,  7, 14, 21, 28, 35, 42, 49])

In [14]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

2. zeros and ones :- Generate arrays of zeros and ones

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. linspace :- return evenly spaced numbers over a specified interval

In [23]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [24]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

4. eye :- creates a identity matrix

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

5. Random :- ways to create random arrays

a. rand :-  create an array of given shape and populate it with random samples from a uniform distribution over [0,1)

In [29]:
np.random.rand(2)

array([0.5065603 , 0.90061688])

In [30]:
np.random.rand(46)

array([0.88642359, 0.51284555, 0.51453473, 0.19270633, 0.43117235,
       0.1953502 , 0.67851802, 0.07037031, 0.08725762, 0.49511129,
       0.56743192, 0.36451122, 0.68553413, 0.11047351, 0.38522895,
       0.80713054, 0.24153213, 0.76127452, 0.67523585, 0.04767539,
       0.0215844 , 0.73965122, 0.53919193, 0.61167769, 0.8254471 ,
       0.1854736 , 0.35477198, 0.22023171, 0.73388552, 0.93403341,
       0.30114577, 0.17930804, 0.08305201, 0.57626641, 0.66392171,
       0.69745613, 0.30316624, 0.52878324, 0.47148174, 0.63542711,
       0.02770006, 0.38533322, 0.69597559, 0.64832905, 0.97214354,
       0.50158685])

In [33]:
np.random.rand(10,10)

array([[0.36985749, 0.22922279, 0.95900004, 0.91412982, 0.45440646,
        0.55896899, 0.13666844, 0.85247611, 0.05980717, 0.98796474],
       [0.56824205, 0.62976798, 0.02520328, 0.23324293, 0.61086684,
        0.60589265, 0.43157771, 0.90203408, 0.15613907, 0.03353848],
       [0.18242715, 0.45159094, 0.39699904, 0.43512088, 0.16741596,
        0.43189582, 0.94762137, 0.37161047, 0.57455422, 0.8928216 ],
       [0.5378521 , 0.00905216, 0.73753033, 0.90908049, 0.7236959 ,
        0.59389447, 0.48739843, 0.43768295, 0.69414881, 0.42513986],
       [0.02298353, 0.67985561, 0.73006903, 0.98861439, 0.43247521,
        0.49397233, 0.68244514, 0.79014394, 0.45224198, 0.42243881],
       [0.87876578, 0.45087875, 0.4561959 , 0.90804736, 0.09442943,
        0.09329967, 0.7132067 , 0.89624553, 0.89237486, 0.0303809 ],
       [0.31435911, 0.9338019 , 0.93600696, 0.80014636, 0.06306689,
        0.6634794 , 0.02247646, 0.93858714, 0.64788586, 0.52757758],
       [0.01590661, 0.8167569 , 0.5919952

b. randn :- Return a sample (or samples ) from "standard normal" distribution .

In [34]:
np.random.randn(2)

array([-0.75556271,  0.83267591])

In [36]:
np.random.randn(45)

array([ 0.63851385, -0.4518037 , -0.48303635,  2.10667196,  1.4054378 ,
        0.39852909,  2.22142071, -1.39427858, -0.17609069,  0.16919945,
        0.46753971,  0.25258042, -1.1991973 , -0.13453675,  0.0816233 ,
        0.22907556,  0.13325448,  0.06353363, -0.85362248,  0.14579312,
        0.88321343, -0.26771347,  0.49569053, -0.62158665, -0.09761883,
       -0.6277701 , -0.46524301,  1.68310303,  0.30393726, -0.50075182,
        0.13912733,  1.3483091 , -0.26803486, -2.07858789,  0.22404105,
       -0.49406936,  0.21717894, -0.97011683, -0.78061801,  0.21562742,
        0.43802372, -0.77776938,  2.53869511,  0.40677134,  1.03436822])

In [38]:
np.random.randn(5,5)

array([[ 0.06830888, -0.54129652,  0.05461506, -0.32802562, -1.01788911],
       [-0.64459445, -0.68517675, -0.30222823,  0.38527617, -1.36099884],
       [-0.39228642, -0.15008353,  0.12318804,  0.27717824, -0.60358899],
       [-1.48579182,  0.73746248, -1.13224705, -0.44825144, -1.40434625],
       [-0.18013832,  1.09800936, -0.33595303,  0.1838324 ,  2.63828835]])

In [40]:
np.random.randn(3,3)

array([[-0.17290448,  0.92930248,  1.77078783],
       [-0.10872797,  0.24151945, -0.11214436],
       [ 1.02008832,  0.18787328,  0.34050667]])

c. randint :- random integers from low (inclusive ) to high (exclusive)

In [41]:
np.random.randint(1,100)

10

In [42]:
np.random.randint(1,599)

423

In [43]:
np.random.randint(0,1000,23)

array([616, 154,  82, 794, 106, 750, 417, 945, 545,  16, 870, 703, 449,
       584, 870, 872, 986, 608, 508, 593, 633, 927, 357])

6. Attributes or Methods

In [44]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [45]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [46]:
print(ranarr)

[ 8 43 23 10 26  8  2 31 16 48]


7. **Reshape** :- returns an array containing the same data with a new shape

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

8. max,min,argmax,argmin

In [49]:
ranarr

array([ 8, 43, 23, 10, 26,  8,  2, 31, 16, 48])

In [50]:
ranarr.max() # gives the element

48

In [51]:
ranarr.argmax() # gives the index

9

In [52]:
ranarr.min()

2

In [53]:
ranarr.argmin()

6

9. Shape :- it is a attribute

In [54]:
arr.shape #vector

(25,)

In [57]:
#notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arr.reshape(25,1).shape

(25, 1)

11. dtype :- grab the datatype of the object inside the given array

In [61]:
arr.dtype

dtype('int64')

**NumPy Operations **

In [62]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr + arr # dimension should match or else array will be out of bound

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [66]:
#warning on divison by zero , but not an error
# just replace with nan
arr/arr

<ipython-input-66-544060550b5e>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
#also warning , but not an error insted infinity
1/arr

<ipython-input-67-a159a3e48a53>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [68]:
arr**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

**Universal Array Functions **

In [69]:
#taking square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
#calculating exponential(e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [73]:
np.max(arr) # same as arr.max()

9

In [75]:
np.min(arr)

0

In [76]:
np.sin(arr) # in radians

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
np.log(arr)

<ipython-input-77-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])